### PR TITLE
Updating new issue template link

### PR DESCRIPTION
**Pull request by earth2marsh**
The old link didn't offer me the template as expected. This suggestion should address that, but please check that it works for you like it does for me!

### CODE REVIEW

**Review by abangser — CHANGES_REQUESTED** [review]
This is great, thanks Marsh! Can you please just do a replace all to cover all languages? This will include Spanish as well now if you rebase off main. 

Thanks!

**Comment by lianmakesthings** [comment]
@abangser with the new flow it won't be necessary to duplicate this anymore

**Review by abangser — APPROVED** [review]
Fantastic that the new flow unblocks this! Just to make it clear, no other language has changed this page so there is no further work to be completed.

**Review by lianmakesthings — APPROVED** [review]

**Review by lianmakesthings — CHANGES_REQUESTED** [review]
The page cannot be built on the deploy preview due to this error:

> 5:46:42 PM: Error: error building site: "/opt/build/repo/website/content/en/blog/contributing-to-wg-platforms.md:1:1": "/opt/build/repo/website/layouts/_default/_markup/render-link.html:4:15": execute of template failed: template: _default/_markup/render-link.html:4:15: executing "_default/_markup/render-link.html" at <urls.Parse>: error calling Parse: parse "[https://github.com/cncf/tag-app-delivery/issues/new](https://github.com/cncf/tag-app-delivery/issues/new?assignees=&labels=proposals&projects=&template=community-contribution.yml&title=%5BCommunity%5D+%3CShort+description%3E)": first path segment in URL cannot contain colon

@earth2marsh would you mind taking a look? Does the page build correctly locally for you?

**Comment by earth2marsh** [comment]
Hmmm, it looks like the URL wasn't entered properly. I don't have a local env to test, but I think my latest commit should be an improvement.

**Review by abangser — COMMENTED** [review]
Link opens right for me on the preview deploy 👍

I did notice the same thing on the `contributing` main page. Not sure if we want to get that into this PR or later.

Also noticed that the github action for i18n shows failure, I wonder if we can make that non-blocking? Will need to investigate but I don't want to see that hold up a PR like this.

**Review by lianmakesthings — APPROVED** [review]

**Comment by lianmakesthings** [comment]
> I did notice the same thing on the contributing main page. Not sure if we want to get that into this PR or later.

Let's do that in another PR

**Pull request merged**
