### PR TITLE
Update website to reflect correct meeting time

### PR DESCRIPTION
**Pull request by lianmakesthings**
We changed the cadence of the meeting, this has not been updated on the website yet.

I made an effort to translate to Chinese, Japanese and Korean with the help of Google translate and my very limited understanding of these languages. Would appreciate a review by fluent speakers 🙏  @node @hhiroshell @Eeap

### CODE REVIEW

**Review by hhiroshell — APPROVED** [review]
@lianmakesthings 
The Japanese translation looks fine to me!👍

**Comment by Eeap** [comment]
If "Every two weeks on Wednesday" means 2nd and 4th week, it looks good to me :).
Also, it looks better word, if you change "2주마다" with "격주".

**Comment by lianmakesthings** [comment]
> If "Every two weeks on Wednesday" means 2nd and 4th week, it looks good to me :)

@Eeap Unfortuntely, not necessarily. It just means in a 2-week cadence, it could be 1st and 3rd. What would be the correct translation for that?

**Comment by Eeap** [comment]
> > If "Every two weeks on Wednesday" means 2nd and 4th week, it looks good to me :)
> 
> @Eeap Unfortuntely, not necessarily. It just means in a 2-week cadence, it could be 1st and 3rd. What would be the correct translation for that?

Then "2주마다" is ok, but it is not natural with following words ("2주마다 수요일" is not natural). So"격주" instead of "2주마다" is better to understand for Korean.

**Review by angellk — APPROVED** [review]
Lgtm

**Pull request merged**
