### PR TITLE
Moving meeting notes into proper place

### PR DESCRIPTION
**Pull request by chris-short**
Meeting artifacts will live here and on YouTube moving

### CODE REVIEW

**Review by scottrigby — APPROVED** [review]
Thanks so much for all this @chris-short! 

Note for others: 
- Chris also helped upload and retitle all the new videos to YouTube 💪 
- We earlier thought we'd put these meeting text chat exports in a Google Drive, but Chris suggested it's best to live somewhere that the WG owns, rather than having to deal with extra permissions. I agree!
- I initially excluded these when moving commits from https://github.com/gitops-working-group/gitops-working-group to this repo. [History on those files is only me](https://github.com/gitops-working-group/gitops-working-group/commits/main/meetings) and I'm happy to reset for this. We'll also be deleting these files from that location once this PR is merged.
- For future we are looking into moving meetings to Bevy via https://community.cncf.io, which may have other options for exporting text chats. We're doing this PR now only to keep up with recent meeting transparency to those who could not attend them in person

**Review by hongchaodeng — APPROVED** [review]

**Comment by lloydchang** [comment]
@chris-short I suggest that you rename `old-monthly` directory to `old` directory in this pull request.

Same reason as my comment at https://cloud-native.slack.com/archives/C01G9DEE88M/p1636184439093800?thread_ts=1636120243.081800

> @chris-short @scottrigby 
>
> I suggest renaming “Working Group Monthly” to “Working Group” to decouple the playlist title from scheduling mechanics.
>
> Less is more.
>
> Scheduling mechanics: They used to be monthly, and they’re now fortnightly. [There is a newish conversation to make them first and third _(or second and fourth)_ week of each month](https://cloud-native.slack.com/archives/C01G9DEE88M/p1635536574025200), which would skip the fifth week.
>
> https://www.youtube.com/playlist?list=PLXOML2VBdIo4-biBmCbfNkP0ywF0f5mau

**Review by lloydchang — CHANGES_REQUESTED** [review]
@chris-short I suggest that you rename `old-monthly` directory to `old` directory in this pull request.

Same reason as my comment at https://cloud-native.slack.com/archives/C01G9DEE88M/p1636184439093800?thread_ts=1636120243.081800

> @chris-short @scottrigby 
>
> I suggest renaming “Working Group Monthly” to “Working Group” to decouple the playlist title from scheduling mechanics.
>
> Less is more.
>
> Scheduling mechanics: They used to be monthly, and they’re now fortnightly. [There is a newish conversation to make them first and third _(or second and fourth)_ week of each month](https://cloud-native.slack.com/archives/C01G9DEE88M/p1635536574025200), which would skip the fifth week.
>
> https://www.youtube.com/playlist?list=PLXOML2VBdIo4-biBmCbfNkP0ywF0f5mau

**Comment by scottrigby** [comment]
@lloydchang let's do renaming as a follow-up. Right now they match the WG meeting notes google doc meeting type headers. I don't have a problem renaming, but should be done together. I don't want this to block archiving github.com/gitops-working-group/gitops-working-group. Would you mind adding that to the next WG meeting agenda?

**Review by thschue — APPROVED** [review]
lgtm

**Comment by scottrigby** [comment]
Hi @thschue, until we are granted write access on this repo (which will be limited to the scope in [CODEOWNERS](https://github.com/cncf/tag-app-delivery/blob/master/CODEOWNERS)) the WG can't merge this ourselves. See https://github.com/cncf/tag-app-delivery/issues/154

If you can merge this one in the meantime, this PR is ready. Thanks!

**Comment by scottrigby** [comment]
@chris-short I just realized this PR was automatically closed when the default branch was changed from master to main. I have the ability to merge gitops-wg PRs now, but this is a GitHub thing. Do you mind cherry-picking your commit into a new PR against `main`?

**Comment by chris-short** [comment]
@scottrigby #181

**Pull request closed without merging**
