### PR TITLE
covered umbrella operator patterns

### PR DESCRIPTION
**Pull request by dmesser**
Signed-off-by: Daniel Messer <dmesser@redhat.com>

### CODE REVIEW

**Review by thschue — COMMENTED** [review]
lgtm

**Comment by Jenniferstrej** [comment]
Very interesting. Lgtm but just wanted to check whether mentioning the term umbrella would be  useful or not. What do you think?

**Comment by dmesser** [comment]
@Jenniferstrej I think it's a good idea, just added a mention in the intro part of this paragraph. Thanks!

**Review by OmerKahani — APPROVED** [review]
Thanks!

**Review by thschue — APPROVED** [review]

**Pull request merged**
