### PR TITLE
add more speakers for tag app delivery in Paris

### PR DESCRIPTION
**Pull request by abangser**
Was reviewing my schedule and realised that we had some more awesome representatives from the group speaking at some of the other colo events. I fear I will have missed someone, but I tried to grab any name from people I know have contributed in the last year.

### CODE REVIEW

**Comment by abangser** [comment]
Great question!

My logic was that there are two other talks on there that feature people involved in the TAG so I'd add anyone else who is engaged in the last 12 months with the TAG. 

I do realise now that the other two had chairs which may have been the previous bar. So if that's the case I can revert that commit and just do the coffees 👍

**Comment by lianmakesthings** [comment]
Three options I see:
1. We only advertise events or talks based on title, not on the people
2. We only advertise events or talks with "official" members, i.e. chairs and TLs
3. We advertise everything we think is related to app delivery (within reason) and/or with folks working with the TAG / WGs

I don't think there's a right answer here, it's whatever we believe makes the most sense for us.
Personally, I prefer option 3. I don't anticipate it to be too overwhelming. Plus, it's nice to give people options and showcase the diversity of the community.

**Comment by joshgav** [comment]
I'm okay with @lianmakesthings' option 3 if all agree, no need to make a big deal of it :D. Approval incoming.

**Review by joshgav — APPROVED** [review]

**Comment by abangser** [comment]
Thanks both! Will merge this as is, and if anything else comes in we can always add 🙌

**Comment by lianmakesthings** [comment]
Thanks for this @abangser 🚀

**Pull request merged**
