### PR TITLE
Add GitOps Days 2022

### PR DESCRIPTION
**Pull request by dholbach**
Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Better late than never

**Review by scottrigby — APPROVED** [review]
This is fine for now 👍 

Ultimately we want to de-duplicate these timeline items that are already on the gitops events list at https://OpenGitOps.dev/events. Might be good to link to that from here when we do ❤️

**Review by scottrigby — CHANGES_REQUESTED** [review]
Actually @dholbach we need to resolve conflicts, otherwise looks good

**Review by scottrigby — APPROVED** [review]
👍

**Pull request merged**
