### PR TITLE
Create 2024-05-20-enterprise-idp-maturity-hack.md

### PR DESCRIPTION
**Pull request by Li-Or-Amir**
New blog - still needs formatting, to be completed by EOW.
Please go ahead and review content here: https://docs.google.com/document/d/1fATY7nHGiQjJ4AZRzna198UJFc5bDLGC/edit?usp=sharing&ouid=102485578350250403020&rtpof=true&sd=true

### CODE REVIEW

**Comment by krumware** [comment]
Related to https://github.com/cncf/tag-app-delivery/issues/643

**Comment by krumware** [comment]
Platforms WG requested this submission via https://github.com/cncf/tag-app-delivery/issues/643#issuecomment-2119869433

**Comment by abangser** [comment]
Hey @lianmakesthings @thschue @angellk this blog should be ready for merge. Please review when you have time. Also note that the date is from the original PR opening (May 20) and can be updated accordingly if we want it set to the date of merge!

**Comment by abangser** [comment]
🎉  @Li-Or-Amir we are all approved. I will leave you the honours. All you need to do is click the `squash and merge` button on this PR and then you will see something like this:
image

You can update the name and body of what gets stored long term. E.g. get rid of `wip` from the title and make for a more general body than all the individual updates that were useful for review, but not for long term storage.

I am happy to do this too if you don't find time in the next day or so, but figure give you the full experience 😄

**Comment by Li-Or-Amir** [comment]
@abangser I don't see this button on my end.
Could it be because I don't have write access to the website?

**Comment by abangser** [comment]
> @abangser I don't see this button on my end. Could it be because I don't have write access to the website?

Doh! Must be a permissions thing. I will merge for you ❤️

**Pull request merged**
