### PR TITLE
rename maturity model folders to readd 3 languages

### PR DESCRIPTION
**Pull request by abangser**
As you can see below, while reviewing #601 I noticed we had lost 3 languages off the platform engineering maturity model view:
image

After investigation I noted a difference in directory name which caused this. After renaming the directories you can see that the languages reappear:
image

### CODE REVIEW

**Comment by angellk** [comment]
@abangser it looks like French is the only one missing now when viewing netlify - could you fix and then we can merge?

**Comment by abangser** [comment]
Thanks for reviewing @angellk ! French is missing as #601 is still outstanding. Once in it will be good to go 🥳

**Review by angellk — APPROVED** [review]
lgtm - just need to make sure French still shows up!

**Comment by abangser** [comment]
That's everyone! 🎉 🇨🇳 🇰🇷 🇯🇵 🇪🇸 🇫🇷

**Comment by RobertKelly** [comment]
Amazing! 👏🏻 🚀 🌏

**Pull request merged**
