### PR TITLE
fixes Image ref in Chinese Platforms Whitepaper

### PR DESCRIPTION
**Pull request by lianmakesthings**
In the Chinese translation of the platforms whitepaper, a non-existing image `platforms-def.drawio.zh.png` is referenced.
This PR displays the English version of the image as long as the chinese version does not exist

@node

### CODE REVIEW

**Comment by node** [comment]
I will check it later . Thank you.
:smile:

**Comment by lianmakesthings** [comment]
Let's go with option 1, then there's no pressure on you to submit the translated image :)

**Review by abangser — APPROVED** [review]
Great find. Also looking forward to the translated version being stored in source control so that we have more durability with the image. 

Thanks!

**Comment by node** [comment]
Created new PR #648 for adding the missing picture.

**Comment by lianmakesthings** [comment]
Closed in favour of #648

**Pull request closed without merging**
