### PR TITLE
Image url is broken - Fix

### LINKED ISSUE #361: Image url is broken
Example Backup Process image in [Operator-WhitePaper_v1-0.md](https://github.com/cncf/tag-app-delivery/blob/main/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md#backup) is missing

### PR DESCRIPTION
**Pull request by aryasoni98**
#361 I just fix the image url.

1: MD file not read the image path.
2: So, I just change the image path.

Screenshot 2023-04-17 at 2 40 46 AM

### CODE REVIEW

**Review by thschue — APPROVED** [review]
lgtm

**Comment by aryasoni98** [comment]
#380 Also resolve the this issue .

@thschue @Jenniferstrej @AloisReitbauer @hongchaodeng @AlexsJones @joshgav 
Please review the both the issue #380 #361

**Comment by aryasoni98** [comment]
Screenshot 2023-04-21 at 1 56 42 PM

Resolve #380

**Review by roberthstrand — APPROVED** [review]

**Comment by roberthstrand** [comment]
@aryasoni98, for this to be merged, could you please go through and make sure that you have signed-off your commits? Details can be found on the [DCO check](https://github.com/cncf/tag-app-delivery/pull/379/checks?check_run_id=12919259372).

**Comment by Jenniferstrej** [comment]
Firstly, thanks Arya Soni for your submission.
I agree @joshgav - this PR is against an older version of the white paper which won't be maintained anymore. Also, it would be good if we found a solution for the links to work on both places rather than breaking the website one, as Josh mentioned.

**Comment by joshgav** [comment]
Per [above comment](https://github.com/cncf/tag-app-delivery/pull/379#pullrequestreview-1406488030) this is actually correct as is, so closing this PR.

**Pull request closed without merging**
