### PR TITLE
Streamline website workflow

### PR DESCRIPTION
**Pull request by lianmakesthings**
This Pull Request introduces multiple ways to streamline the process of adding content to the website
- adds manifest to run the webserver in a development container
- adds hugo archetypes to streamline creation of blogposts, contributions, and working groups
- updates documentation to explain new processes

### CODE REVIEW

**Comment by abangser** [comment]
This is awesome, thanks so much @lianmakesthings !

I can confirm I have been tried to:
- [x] follow the readme to start up a devcontainer locally with the code. 
- [x] create a new call for contribution using the template
- [x] create a new blog using the template
- [ ] create a new working group using the template

I was not able to create the wg and got the following error:
```
$ hugo new wgs/blah
Error: failed to resolve "wgs/blah" to an archetype template
```

One thing I think we should include in the Readme is also how to clean up local development environments if using devpod. It is fairly easy to track down with the CLI but would make for a more friendly first experience.

**Comment by lianmakesthings** [comment]
> I was not able to create the wg and got the following error:
> 
> ```
> $ hugo new wgs/blah
> Error: failed to resolve "wgs/blah" to an archetype template
> ```

Interesting.. it works for me
```
node ➜ /workspaces/tag-app-delivery/website (streamline-website-workflow) $ hugo new wgs/blah
WARN  DEPRECATED: Kind "taxonomyterm" used in disableKinds is deprecated, use "taxonomy" instead.
WARN  config: languages.en.description: custom params on the language top level is deprecated and will be removed in a future release. Put the value below [languages.en.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
Content dir "/workspaces/tag-app-delivery/website/content/wgs/blah" created
```
From which repo are you starting the workspace?
If you're pointing at the remote repo, it might now work as this PR has not been merged to main yet.

**Comment by lianmakesthings** [comment]
@abangser I just did another text and verified that if you use the button in the readme, it will always use the remote repositories main branch.
Could you test it again with either the CLI path or creating a workspace manually through the GUI from your local git repository (with the right branch)?

**Comment by abangser** [comment]
So I am not 100% sure I follow your suggestions in the last two posts since I was always using the CLI. But at the same time I ran the command just now and all is good!

Therefore I see no blockers on this 🙌 The only question is if the TAG leadership is happy with devcontainers as the tech for the website!

**Comment by lianmakesthings** [comment]
The devcontainers are not necessaary for development of the website, I just added the files on top, because I work with them.
The rest of the flow works exactly the same if you run the site locally

**Review by thschue — APPROVED** [review]
lgtm

**Pull request merged**
