### PR TITLE
Make the tab switcher of the maturity model table work in the translated version.

### PR DESCRIPTION
**Pull request by hhiroshell**
This PR makes the tab switcher of the model table work even if the tab names are written in multi-byte characters. Currently, this issue is occurring in the Chinese version.

And I have also made the same change in the English version. This is to ensure that there will be no issues when translations are added in the future by copying from the English version.

- [x] Local test done
- [x] Reviews by Chinese speakers

### CODE REVIEW

**Review by abangser — COMMENTED** [review]
> And I have also made the same change in the English version. This is to ensure that there will be no issues when translations are added in the future by copying from the English version.

This is fantastic, thank you!

And I can confirm it technically works as expected for both Chinese and English. Looking for a review for the language and then should be good to go!

**Comment by hhiroshell** [comment]
@node 
Could you please check the change or involve other Chinese speakers?

**Comment by node** [comment]
> @node Could you please check the change or involve other Chinese speakers?

Let me check it 😄

**Review by node — APPROVED** [review]
LGTM. 
This works well both in Chinese and English. Thanks for your contribution 👍

**Review by roberthstrand — APPROVED** [review]

**Pull request merged**
