### PR TITLE
Adding note for the maturity model

### PR DESCRIPTION
**Pull request by earth2marsh**
Using the `pageinfo` shortcode as discussed in Slack

### CODE REVIEW

**Comment by earth2marsh** [comment]
missed the v1 file in this PR. fixing...

**Review by abangser — APPROVED** [review]
Looks great, thanks @earth2marsh!

I have added the same change to the 3 translated pages (ja, ko, and zh). Japanese is only metadata translated, but I think we will want to call out to the KO and ZH contributors that this has been added in case they want to translate properly.

**Comment by lianmakesthings** [comment]
calling @node @hhiroshell @Eeap to see if you have interest & bandwidth to translate this (can be in a separate PR)

**Comment by abangser** [comment]
> can be in a separate PR

Likely _should_ be! I think there is big value in getting the right language in, but I don't want to wait on that if this is ready to go as we at least have the info there!

**Review by lianmakesthings — APPROVED** [review]

**Comment by hhiroshell** [comment]
@lianmakesthings @abangser 

> calling @node @hhiroshell @Eeap to see if you have interest & bandwidth to translate this (can be in a separate PR)

I'll create a PR for the Japanese. 👍
But please wait until I return from GW vacation.

※ GW: https://en.wikipedia.org/wiki/Golden_Week_(Japan)

**Comment by hhiroshell** [comment]
@lianmakesthings @abangser

After taking some time to think about it, I realized that the Japanese white paper has not been translated yet. 😅 
So, I'll create a PR to translate the entire paper, including the note. Please let me spend adequate time on this.

**Comment by abangser** [comment]
Absolutely fair @hhiroshell, we would love to see it, but also understand the big task so do take your time and let us know if we can help in any way! Thanks 🎉

**Pull request merged**
