### PR TITLE
Add Keycloak to Example CNCF/CDF Projects

### PR DESCRIPTION
**Pull request by y-tabata**
This PR proposes adding Keycloak to Example CNCF/CDF Projects of Identity and secret services Capability in CNCF Platforms White Paper.
Keycloak is a CNCF incubating project and an identity and access management OSS.

### CODE REVIEW

**Review by joshgav — APPROVED** [review]
LGTM, thanks!

**Comment by y-tabata** [comment]
@joshgav Thank you for reviewing! Are there any other things to do to proceed with this PR?

**Comment by joshgav** [comment]
@y-tabata nope, thanks for the reminder! Merged.

**Comment by y-tabata** [comment]
@joshgav Thanks!

**Pull request merged**
