### PR TITLE
Contributions page

### PR DESCRIPTION
**Pull request by abangser**
We get a lot of questions about where to start with the TAG or a WG. This page is a great location for us to start supporting people with an easier path into the groups.

@techmaharaj and I put together a draft of something we could add here to get started.

### CODE REVIEW

**Comment by lianmakesthings** [comment]
Great work! Thanks for taking this on 👏

**Review by lianmakesthings — APPROVED** [review]

**Comment by abangser** [comment]
Thank you for the rapid review @lianmakesthings !! 

I have added another commit so will wait for more reviews. I was thinking of making this commit on a new PR, but decided it is connected enough to add here. I can of course pull it out if it is more controversial.

This commit is thanks in large part to @earth2marsh and will help us continue to support new authors with more transparency and clarity on what it means to contribute!

**Review by joshgav — APPROVED** [review]
Thank you for this @abangser and @techmaharj!

LGTM when you're happy with it!

**Comment by abangser** [comment]
Awesome! Given the double review I am inclined to merge now and update later. For example, we may extend this to include taxonomy descriptions as mentioned in #518 but I think that is likely a month out so not necessary to hold this PR up for that.

Thanks all both for the contributions and speedy reviews!

**Pull request merged**
