### PR TITLE
adding product-as-a-platform folder and interview script

### PR DESCRIPTION
**Pull request by mluskind**
- added platform-as-a-product folder
- added platform eng interview script to paap folder

### CODE REVIEW

**Comment by abangser** [comment]
Heyya @mluskind, we'll get a TAG review soon, but in the mean time would you mind following the directions on the DCO failure? It is a requirement before we can merge. 

Thanks!

**Review by abangser — APPROVED** [review]
Very glad to have this entering source control 🙌🎉

I am happy with the directory here, or having it nested under the `platforms-wg` directory. I'd default to leaving it here unless someone in the TAG prefers we nest it.

**Comment by angellk** [comment]
> Very glad to have this entering source control 🙌🎉
> 
> I am happy with the directory here, or having it nested under the `platforms-wg` directory. I'd default to leaving it here unless someone in the TAG prefers we nest it. 

Agree to leaving here vs nested

**Review by angellk — APPROVED** [review]
Lgtm

**Pull request merged**
