### PR TITLE
website: Add initial Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by gtirloni**
Includes commits from #528

### CODE REVIEW

**Comment by joshgav** [comment]
Thank you for this @gtirloni! Do you know a Portuguese speaker who could do a review for us? It would be good to get at least one other reviewer who's comfortable with the language.

@levenhagen could you perhaps help out here, or do you have someone you might recommend? Thank you!

**Comment by abangser** [comment]
@kirederik maybe?

**Comment by kirederik** [comment]
on it

**Comment by levenhagen** [comment]
hey @joshgav! (was on vacation, sorry)
most definitely, I can help reviewing it too. I'll have a look tomorrow

**Comment by gtirloni** [comment]
Thanks, please let me know if I can make this review easier for you.

**Comment by gtirloni** [comment]
@bcap would you have bandwidth to review this PR? Just a shot in the dark here :-)

**Review by angellk — APPROVED** [review]
Thank you for your contributions @gtirloni - please feel free to add more and we'll make sure the next reviews are quicker :)

**Comment by angellk** [comment]
@gtirloni please remove symlinks and we can re-merge!

**Comment by abangser** [comment]
Not sure if we need to reopen this in some way? Also want to reference this help from Chris! https://github.com/cncf/tag-app-delivery/issues/573#issuecomment-1980476287

**Pull request merged**
