### PR TITLE
Kubecon NA 2024 info and schedule

### PR DESCRIPTION
**Pull request by krumware**
This adds a blog page for the Kubecon NA 2024 schedule announcement and call for lightning talks.

Please add details in comments so that they can be added.

Before this can be merged we need: 
* locations and times of talks performed by chairs and other key working group members
* other notable schedule items

Lighning Talks can be added to the schedule in the form of another PR.

### CODE REVIEW

**Comment by roberthstrand** [comment]
The Platforms WG hosts a daily "Platform Coffee" meetup at Cupla Coffee (77 W 200 S).
Tuesday through Friday, 07:15 - 08:30.

**Comment by techmaharaj** [comment]
Let me know if this helps @krumware. Found all the talks from community folks at PE Day and PE track.

| **Time & Location** 	| **Session** 	| **Presented By** 	|
|---	|---	|---	|
| Tuesday November 12, 2024 10:40am - 11:05am MST  <br>Salt Palace \| Level 1 \| Grand Ballroom G 	| Portals and Platforms, Two Ps in a Pod? How Good Interfaces Make for Good <br>Operability  	| Jorge Lainfiesta, Rootly & Abby Bangser, Syntasso 	|
| Tuesday November 12, 2024 11:15am - 11:25am MST  <br>Salt Palace \| Level 1 \| Grand Ballroom G 	| Lightning Talk: Are You Really Ready to Adopt a Platform? 	| Atulpriya <br>Sharma, InfraCloud Technologies 	|
| Wednesday November 13, 2024  5:25pm -  6:00pm MST  <br>Salt Palace \| Level 1 \| Grand Ballroom H 	| Creating Paved Paths for Platform Engineers 	| Ritesh Patel, Nirmata; Abby <br>Bangser, Syntasso; Viktor Farcic, Upbound; Nicholas Morey, Akuity; <br>Praseeda Sathaye, Amazon 	|
| Friday November 15, 2024 11:00am - 11:35am MST  <br>Salt Palace \| Level 1 \| Grand Ballroom H 	| Platform Engineering in Financial Institutions: The Practitioner Panel 	| Paula <br>Kennedy, Syntasso; Chris Plank, NatWest Bank; Suhail Patel, Monzo; <br>Jinhong Brejnholt, Saxo Bank; Rachael Wonnacott, Fidelity International 	|
|  	|  	|  	|

**Comment by roberthstrand** [comment]
@krumware, could you get these suggestions in, then we can merge and share this? We can just update this as we get more.

**Comment by krumware** [comment]
@roberthstrand ready for you

**Review by roberthstrand — APPROVED** [review]

**Pull request merged**
