### PR TITLE
Update the term "Translation" to "Localization"

### LINKED ISSUE #689: [Feature Request] Update the term "Translation" to "Localization"
## Background

In cncf/tag-app-delivery, the term "Translation" is currently used. While I think "Translation" is a good term, I think "Localization" is more appropriate same as other cncf and kubernetes repositories.

ref. https://github.com/cncf/tag-app-delivery/pull/673#discussion_r1628032222

> cc maintainers
> 
> IMO, "Localization" `(ローカライゼーション)` is a more appropriate term than "Translation" `(翻訳)`.
> 
> These words are very similar, but Localization involves not just translation, but also respecting and adapting to the local region and culture.
> 
> Additionally, many CNCF and Kubernetes projects use the term "Localization" instead of "Translation".

## Feature Description

- Update the term "Translation" to "Localization" (in the `/website`)

### PR DESCRIPTION
**Pull request by Okabe-Junya**
close #689 

## Change List

- Update the term "Translation" to "Localization" (in the `/website`)

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
cc @abangser 

(ref. https://cloud-native.slack.com/archives/CL3SL0CP5/p1717618616261299?thread_ts=1717604563.468949&cid=CL3SL0CP5)

**Review by abangser — APPROVED** [review]
Thanks for fixing this!

**Review by ynora — APPROVED** [review]
LGTM

**Review by thschue — APPROVED** [review]
lgtm

**Pull request merged**
